[project]
name = "vdeps"
version = "0.1.0"
dependencies = [
    "tomli; python_version < \"3.11\"",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = "."

